### ISSUE TITLE
ask about the project

### ISSUE THREAD

**Issue by thaisonmq** [khoa288/id-chip-reader#1]
what product are you using to read NFC, does the program work like the video?

**Comment by khoa288** [comment]
Hi @thaisonmq, the product used for NFC reading in the video is the Sony FeliCa RC-S380/S. I have also tested the program with the Gemalto USB Smart Card Reader. You can find the code for the interaction with the reader (Connect, Read, Send, etc.) in `utils/reader.c`. The program should work with other readers as well, though you might need to make minor code changes in this file based on your reader's API. The rest of the code handles the logic for reading Identification Card Chips, which should be consistent across different readers as per the ICAO Doc 9303 standards.
